bansospeduli/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

import beranda.urls as beranda
import distribusi.urls as distribusi
import laporan.urls as laporan
import registration.urls as registration
import staff.urls as staff
import user.urls as user
from beranda.views import beranda as beranda_index

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', beranda_index),
    path('beranda/', include(beranda)),
    path('distribusi/', include(distribusi)),
    path('laporan/', include(laporan)),
    path('registration/', include(registration)),
    path('staff/', include(staff)),
    path('user/', include(user)),
]

beranda/urls.py
from django.urls import path
from .views import beranda, covid_api, login_beranda, logout_account

app_name = 'beranda'

urlpatterns = [
    path('', beranda, name='beranda'),
    path('login', login_beranda, name = 'login'),
    path('covid_api', covid_api, name = "covid_api"),
    path('logout/', logout_account, name='logout_beranda')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from laporan.views import get_bansos_info
from .views import *

urlpatterns = [
    path('flutter/test/', flutter_test),
    path('flutter/login/', flutter_user_login),
    path('dashboard/',dashboard, name = 'dashboard'),
    path('dashboard/mybansos',mybansos,name = 'mybansos'),
    path('',dashboard, name = 'dashboard'), 
    path('dashboard/history',history,name ='history'), 
    path('edit_note', edit_note, name='edit_note'),
    path('flutter/login/', flutter_user_login),
    path('flutter/logout/', flutter_user_logout),
    path('flutter-get-user-info/',flutter_get_user_info),
    path('flutter-update-user/',flutter_update_user),
    path('flutter-user-bansos/',get_user_bansos),
    path('flutter-user-info-bansos/',get_user_bansos_info),
    path('flutter-user-detail-bansos/',user_bansos_from_id)
]

laporan/models.py
from django.db import models
import uuid, datetime
from django.utils import timezone
import pytz

# Create your models here.
def default_time(): 
    tz = pytz.timezone("Asia/Jakarta")
    return datetime.datetime.now(tz) + datetime.timedelta(days=2)

class Laporan(models.Model):
    reporting_user = models.ForeignKey("user.AccountMasyarakat", on_delete=models.CASCADE, default=None)
    reported_bansos = models.ForeignKey("distribusi.Bansos", on_delete=models.CASCADE, default=None)
    report_category = models.CharField(max_length=15, default='')
    report_message = models.TextField(blank=True)
    status = models.BooleanField(default=False)
    laporan_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    verifying_admin = models.ForeignKey("staff.Admin", on_delete=models.SET_DEFAULT, default=None)
    cooldown = models.DateTimeField(default=default_time)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import uuid

class MyAccountManager(BaseUserManager):
    def create_user(self, telephone, password=None):
        if not telephone:
            raise ValueError("Users must have a telephone number")
        
        user = self.model(
            telephone=telephone,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, telephone, password):
        user = self.create_user(
            telephone=telephone,
            password=password,
        )
        user.is_staff = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    telephone = models.CharField(max_length=20,primary_key=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_citizen = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    USERNAME_FIELD = 'telephone'
    REQUIRED_FIELDS = []
    
    objects = MyAccountManager()

    def __str__(self):
        return self.telephone
    
    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return True

# Create your models here.
class AccountMasyarakat(models.Model):
    owning_user = models.OneToOneField(Account, on_delete=models.CASCADE, primary_key=True)
    is_verified = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    NIK = models.CharField(max_length=16)
    SKTMLink = models.CharField(max_length=200)
    bukuTabunganLink = models.CharField(max_length=200)
    partOf = models.ForeignKey("distribusi.Area", 
        on_delete=models.RESTRICT, 
        default='NULL'
    )
    verifying_admin = models.ForeignKey("staff.Admin", on_delete=models.SET_DEFAULT, default=None)

user/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate,logout,login
from distribusi.models import *
from django.core.paginator import Paginator
from django.contrib.auth import logout
import uuid
from staff.models import Admin
from .models import *
from laporan.forms import LoginForm
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, HttpResponseForbidden, JsonResponse
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib.sessions.backends.db import SessionStore
from django.views.decorators.csrf import csrf_exempt
import json
from django.conf import settings
from importlib import import_module

@login_required()
def dashboard(request):
    # Add additional variable if admin is a tracking admin and is currently occupied
    user = request.user
    try:
        user = AccountMasyarakat.objects.get(owning_user=user)
    
    except AccountMasyarakat.DoesNotExist:
        return HttpResponseForbidden()

    akun = AccountMasyarakat.objects.get(owning_user = user )
    account = akun
    bansos = Bansos.objects.filter(received_by = request.user.telephone)
    response = {'bansos': bansos, 'account':account}
    
    return render(request, 'dashboard.html', response)

@login_required()
def mybansos(request):
    user = request.user
    try:
        user = AccountMasyarakat.objects.get(owning_user=user)
    
    except AccountMasyarakat.DoesNotExist:
        return HttpResponseForbidden()
    
    akun = AccountMasyarakat.objects.get(owning_user = user )
    user = request.user
    bansosgrup = BansosGroup.objects.filter(status = 'queued') | BansosGroup.objects.filter(status = 'sent')
    que = request.GET.get('queued')
    sent = request.GET.get('sent')
    
    if que == 'queued':
        bansos_queue = Bansos.objects.filter(owning_group__status = 'queued',received_by = user.telephone)
        bansosgrup = BansosGroup.objects.filter(status = 'queued').order_by('id_bansos_group')
        bansos_queue_page = Paginator(bansosgrup,1)
        page_num = request.GET.get('page')
        page = bansos_queue_page.get_page(page_num)
        account = akun
        bansosprev = BansosPreviousLocation.objects.filter(bansos_group__status = 'queued')
        response = {'page' : page,  'bansosqueue': bansos_queue, 'bansos_queue_page' : bansos_queue_page, 'prevloc': bansosprev,'account':account}
        return render(request,'mybansos.html',response)
    
    elif sent == 'sent':
        bansos_queue = Bansos.objects.filter(owning_group__status = 'sent',received_by = user.telephone)
        bansosgrup = BansosGroup.objects.filter(status = 'sent').order_by('id_bansos_group')
        bansos_queue_page = Paginator(bansosgrup,1)
        page_num = request.GET.get('page')
        page = bansos_queue_page.get_page(page_num)
        account = akun
        bansosprev = BansosPreviousLocation.objects.filter(bansos_group__status = 'sent')
        response = {'page' : page,  'bansosqueue': bansos_queue, 'bansos_queue_page' : bansos_queue_page,'prevloc': bansosprev,'account':account}
        return render(request,'mybansos.html',response)
    
    else:
        bansos_queue = Bansos.objects.filter(owning_group__status = 'queued',received_by = user.telephone) | Bansos.objects.filter(owning_group__status = 'sent',received_by = user.telephone)
        bansosgrup = BansosGroup.objects.filter(status = 'queued').order_by('id_bansos_group') | BansosGroup.objects.filter(status = 'sent').order_by('id_bansos_group')
        # prevloc = BansosPreviousLocation.objects.filter(bansos_group = Bansos.objects.filter(owning_group__status = 'queued').values(uuid.UUID('owning_group')).first()).first()
        bansos_queue_page = Paginator(bansosgrup,1)
        page_num = request.GET.get('page')
        page = bansos_queue_page.get_page(page_num)
        account = akun
        bansosprev = BansosPreviousLocation.objects.filter(bansos_group__status = 'queued') | BansosPreviousLocation.objects.filter(bansos_group__status = 'sent')
        response = {'page' : page,  'bansosqueue': bansos_queue, 'bansos_queue_page' : bansos_queue_page,'prevloc':bansosprev,'account': account}
        return render(request,'mybansos.html',response)
    

@login_required()
def history(request): 
    user = request.user

    try:
        user = AccountMasyarakat.objects.get(owning_user=user)

    except AccountMasyarakat.DoesNotExist:
        return HttpResponseForbidden()

    user = request.user
    akun = AccountMasyarakat.objects.get(owning_user = user )
    receivedBansos = Bansos.objects.filter(owning_group__status = 'received', received_by = user.telephone)
    previousLocation = BansosPreviousLocation.objects.filter(bansos_group__status = 'received').all()
    response = {'receivedBansos': receivedBansos,'previousLocation':previousLocation,'account':akun}
    return render(request, 'history.html',response)

def edit_note(request):
    if (request.method == "POST"):
        nomor = request.POST.get("id")
        sktm = request.POST.get("sktm")
        buku = request.POST.get("buku")

        akun = AccountMasyarakat.objects.get(owning_user__telephone = nomor)
        akun.SKTMLink = sktm
        akun.bukuTabunganLink = buku
        # akun.is_verified = False
        akun.save()
    return HttpResponseRedirect("/user/dashboard")

## FLUTTER API ##
@csrf_exempt
def flutter_user_login(request):
    if request.method == "POST":
        data = request.body.decode("utf-8")
        cleaned_data = json.loads(data)
        telephone = cleaned_data["telephone"]
        password = cleaned_data["password"]
        
        user = authenticate(request, telephone=telephone, password=password)
        
        if user:
            login(request, user)
            try:
                admin = user.admin
                return JsonResponse({"session-id": request.session.session_key, "is_admin": True, "is_citizen": False, "type":admin.type, "telephone":admin.owning_user.telephone})
            
            except Admin.DoesNotExist:
                return JsonResponse({"session-id": request.session.session_key, "is_admin": False, "is_citizen": True, "telephone": user.telephone, "is_verified": user.accountmasyarakat.is_verified})
        else:
            return HttpResponseForbidden()


def flutter_test(request):
    id = request.GET.get("sessionid")
    engine = import_module(settings.SESSION_ENGINE)
    sessionstore = engine.SessionStore
    session = sessionstore(id)

@csrf_exempt
def flutter_user_logout(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode("utf-8"))
        session_id = data.get('session_id')

        engine = import_module(settings.SESSION_ENGINE)
        sessionstore = engine.SessionStore
        session = sessionstore(session_id)

        session.flush()

        return JsonResponse({'isLoggedOut':True}, safe=False)

def flutter_get_user_info(request):
    if request.method == 'GET':
        data = request.GET
        session_id = data.get('session_id')
        engine = import_module(settings.SESSION_ENGINE)
        sessionstore = engine.SessionStore
        session = sessionstore(session_id)
        user_telephone = session.get('_auth_user_id')
        corresponding_account = Account.objects.get(telephone=user_telephone)
        akun = AccountMasyarakat.objects.get(owning_user = corresponding_account )
        tes = ''
        if akun.is_verified:
            tes = 'VERIFIED'
        else:
            tes = 'UNVERIFIED'
        
        data_dictionary = {
            'name': akun.name,
            'NIK':akun.NIK,
            'SKTM' : akun.SKTMLink,
            'BukuTabungan': akun.bukuTabunganLink,
            'Area': akun.partOf.area_name,
            'verification' : tes
            

        }

        return JsonResponse(data_dictionary, safe=False)
@csrf_exempt
def flutter_update_user(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body.decode("utf-8"))
            session_id = data.get('session_id')
            engine = import_module(settings.SESSION_ENGINE)
            sessionstore = engine.SessionStore
            session = sessionstore(session_id)
            user_telephone = session.get('_auth_user_id')
            corresponding_account = Account.objects.get(telephone = user_telephone)
            akun = AccountMasyarakat.objects.get(owning_user = corresponding_account)
            akun.SKTMLink = data.get('sktm')
            akun.bukuTabunganLink = data.get('buku')
            akun.is_verified = False
            akun.save()
            return JsonResponse({'isSuccessful':True},safe = False)
        except Exception as E:
            return JsonResponse({'isSuccesful':False,'error': str(E)},safe = True)
            
@csrf_exempt
def get_user_bansos(request):
    # Get all bansos group
    data = json.loads(request.body.decode('utf-8'))
    session_id = data.get('sessionId')
    engine = import_module(settings.SESSION_ENGINE)
    sessionstore = engine.SessionStore
    session = sessionstore(session_id)
    user_telephone = session.get('_auth_user_id')
    user = AccountMasyarakat.objects.get(owning_user=user_telephone)
    bansosgroup = Bansos.objects.filter(owning_group__status = 'received', received_by = user)
    all_bansos_list = []
    for grup in bansosgroup:
        group = grup.owning_group
        previous_locations = BansosPreviousLocation.objects.filter(bansos_group = group,status = 'received')
        for prev in previous_locations:
            s = prev.time_stamp
        group_dict = {
            "pk":str(group.id_bansos_group),
            "fields": {
            "responsible_admin": group.responsible_admin.owning_user.telephone,
            "receiving_provinsi":group.receiving_provinsi.area_name,
            "status":group.status,
            "destination_kelurahan":group.destination_kelurahan,

user/templates/history.html
{% extends 'base8000.html' %}
{% block head %}
{% endblock %}
{% block title %}History{% endblock %}
{%block nav%}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown">
    Dashboard
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="/user">My Profile</a></li>
    <li><a class="dropdown-item" href="/user/dashboard/mybansos">MyBansos</a></li>
    <li><a class="dropdown-item" href="/user/dashboard/history">History</a></li>
  </ul>
</li>
{%if account.is_verified%}
<li class="nav-item">
  <a class="nav-link" href="/laporan" role="button">
    Report Bansos
  </a>
</li>
{%endif%}
{%endblock%}
{%block rightnav%}
    <li class="nav-item">
        <div class="nav-link" style="color:white;">
            Hello, {{ account.name }} 
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:logout_beranda' %}">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF" class="svg-as-button"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/></svg>
        </a>
    </li>
{%endblock%}
  <style>
  </style>
{% block body %}

<div class="table-responsive" style ="margin-top:10px">
{%if account.is_verified%}
    <a href="../../../laporan"><buttontype="button" class="btn btn-warning" style = 'margin:10px;width:100px;' >REPORT!</button></a>
    {%endif%}
        {% for i in receivedBansos%}
        <hr>
          <details style="margin-bottom:20px;margin-left:20px">
          <summary>
          {{i.owning_group.id_bansos_group}}
          </summary>
          <table class="table table-sm" >
            <thead>
              <tr>
                <th scope="col md-6" width='100px' >#</th>
                <th scope="col md-6"width='300px' >Name</th>
                <th scope="col md-6"width='200px' >Qty</th>
                <th scope="col md-6"width='200px' >Unit</th>
                <th scope "col md-6" width='200px'> Time </th>
              </tr>
            </thead>
            <tbody>
            {% for x,y in i.owning_group.bentuk_bantuan.items %}
              {% for m,n in i.owning_group.satuan_bantuan.items%}
              {%if x == m%}
              <tr>
                <th scope="row"></th>
                <td>{{x}}</td>
                <td>{{y}}</td>
                <td>{{n}}</td>
                {% for k in previousLocation %}
                {% if k.bansos_group.id_bansos_group == i.owning_group.id_bansos_group and k.status == 'RECEIVED'%}
                <td>{{k.time_stamp}}</td>
                {%endif%}
                {%endfor%}
                
              {%endif%}
              </tr>
              {% endfor %}
              {% endfor %}
            </tbody>
          </table>

          </details>
                    {% endfor %}
    </div> 

{% endblock %}

user/templates/mybansos.html
{% extends 'base8000.html' %}
{% block head %}
    {% load static %}
     <link rel="stylesheet" href="{% static 'distribusi/distribusi-bansos.css' %}">
    {% comment %} <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script> {% endcomment %}
{% endblock %}
{% block title %}My Bansos{% endblock %}
{% comment %} <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>tes</title>
  
  </head> {% endcomment %}
  <style>

  </style>
{%block nav%}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown">
    Dashboard
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="/user">My Profile</a></li>
    <li><a class="dropdown-item" href="/user/dashboard/mybansos">MyBansos</a></li>
    <li><a class="dropdown-item" href="/user/dashboard/history">History</a></li>
  </ul>
</li>
{%if account.is_verified%}
<li class="nav-item">
  <a class="nav-link" href="/laporan" role="button">
    Report Bansos
  </a>
</li>
{%endif%}
{%endblock%}
{%block rightnav%}
    <li class="nav-item">
        <div class="nav-link" style="color:white;">
            Hello, {{ account.name }} 
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:logout_beranda' %}">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF" class="svg-as-button"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/></svg>
        </a>
    </li>
{%endblock%}
  {% comment %} <body> {% endcomment %}
{% block body %}
  
  <div>
  <form method="get" id ="sbform" action=''>
  {% comment %} <select name="status" id="id_status">
        <option value="none" selected disabled hidden>
          Select an Option
            <option value ="all">ALL</option>  
      </option>
        <option value="queued">QUEUED</option>
        <option value="sent">SENT </option>
  </select> {% endcomment %}
  <button type="submit" class="btn btn-outline-primary" style="margin-left : 15px;margin-top:15px; margin-bottom:15px;" value='all' name='all'>All</buttoN>
  <button type="submit" class="btn btn-outline-primary" style="margin-top:15px;margin-bottom:15px;" value ='queued'name='queued'>Queue</button>
  <button type="submit" class="btn btn-outline-primary" style="margin-top:15px;margin-bottom:15px;" value='sent' name='sent'>Sent</buttoN>
  {% comment %} <select name ="status" id= "id_status">
  <option value ="all">---------</option>  
  <option value="queued" label=> QUEUED </option>
  <option value="sent" > SENT </option>
  </select> {% endcomment %}
  </form>
  </div>
  <div class ='col-md-6' style="padding-left:15px">
  {% if not page.object_list %}
  
<div class="alert alert-success" role="alert" style="margin-top:20px;margin-left:10px;">
  <h4 class="alert-heading">None!</h4>
  <p>You do not have anything right now.</p>
  <hr>

</div>
  {%endif%}
    {% for bans in page.object_list%}
      {% for bansos in bansosqueue%}

        {% if bansos.owning_group.id_bansos_group == bans.id_bansos_group %}
        


        <div class="project-info-box">    
          <h2 style ="color : #348ceb"> Bansos Detail </h2>
          <hr></hr>
          <p><b>Responsible Admin     :</b> {{bansos.owning_group.responsible_admin.name}}</p>
          <p><b>ID BansosGroup        :</b> {{bansos.owning_group.id_bansos_group}}</p>
          <p><b>Receiving Area        :</b> {{bans.receiving_provinsi.area_name}}</p>
          <p><b>Status                :</b> {{bansos.owning_group.status}}</p>
          <p><b>Kelurahan             :</b> {{bansos.owning_group.kelurahan}}</p>
          <p><b>Kecamatan             :</b> {{bansos.owning_group.kecamatan}}</p>
          <p><b>Provinsi              :</b> {{bansos.owning_group.provinsi}}</p>
          <p><b>Destination Kelurahan :</b> {{bans.destination_kelurahan}}</p>
          <p><b>Destination Kecamatan :</b> {{bansos.owning_group.destination_kecamatan}}</p>
          <p><b>Destination Kabupaten :</b> {{bansos.owning_group.destination_kabupaten_kota}}</p>
          <p><b>Bentuk Bantuan        :</b></p>
          
           <ul class="list-group">
            {% for x,y in bansos.owning_group.bentuk_bantuan.items%}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                {{x}}
              <span class="badge rounded-pill bg-info text-dark">{{y}}</span>
              </li>
            {% endfor %}
            </ul>
        </div>
        <!-- / project-info-box -->
        {% comment %} <h5>Responsible Admin : {{bansos.owning_group.responsible_admin.name}}
        <h5>ID BANSOSGROUP: {{bansos.owning_group.id_bansos_group}}
        <h5>Receiving Area : {{bans.receiving_provinsi.area_name}}
        <h5>Status : {{bansos.owning_group.status}} </h5>
        <h5>Kelurahan: {{bansos.owning_group.kelurahan}}
        <h5>Kecamatan: {{bansos.owning_group.kecamatan}}
        <h5>Provinsi : {{bansos.owning_group.provinsi}} </h5>
        <h5>Destination Kelurahan: {{bans.destination_kelurahan}}</h5>
        <h5>Destination Kecamatan: {{bansos.owning_group.destination_kecamatan}}</h5>
        <h5>Destination Kabupaten : {{bansos.owning_group.destination_kabupaten_kota}} </h5> {% endcomment %}
    <h2 style ="color : #348ceb;">Bansos Previous Location </h2>
      {%for x in prevloc%}
        {%if x.bansos_group.id_bansos_group == bans.id_bansos_group%}
    <div class="project-info-box">    

        <p><b>Kelurahan  :</b> {{x.kelurahan}}</p>
        <p><b>Kecamatan  :</b> {{x.kecamatan}}</p>
        <p><b>Provinsi   :</b> {{x.provinsi}}</p>
        <p><b>Status     :</b> {{x.status}}</p>
        <p><b>Time       :</b> {{x.time_stamp}}</p>

{% comment %}         
        <h5> Kelurahan : {{x.kelurahan}} </h5>
        <h5> Kecamatan : {{x.kecamatan}} </h5>
        <h5> Provinsi : {{x.provinsi}} </h5>
        <h5> Status : {{x.status}} </h5>
        <h5> Time : {{x.time_stamp}} </h5> {% endcomment %}
                </div>
        {%else%}
        {%endif%}
        
        {%endfor%}
        {%endif%}
        {%endfor%}
        {% endfor %}

    </div>

    <nav aria-label="Page navigation example" style ="padding:15px;">
      <ul class="pagination">
        {% if page.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'mybansos' %}?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="{% url 'mybansos' %}?page={{ page.next_page_number }}">Next</a></li>
        {% endif %}
      </ul>
    </nav>
    {% comment %} <div class="page-links" >
        {% if page.has_previous %}
        <a href="{% url 'mybansos' %}?page={{ page.previous_page_number }}">Previous Page</a>
        {% endif %}
        {% if page.has_next %}
        <a href="{% url 'mybansos' %}?page={{ page.next_page_number }}">Next Page</a>
        {% endif %}
    </div> {% endcomment %}
    
    {% comment %} function getOption() {
  console.log(document.getElementById('id_status').value);
} {% endcomment %}
   
    {%endblock%}
  {% comment %} </body>
  
</html> {% endcomment %}
 