bansospeduli/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

import beranda.urls as beranda
import distribusi.urls as distribusi
import laporan.urls as laporan
import registration.urls as registration
import staff.urls as staff
import user.urls as user
from beranda.views import beranda as beranda_index

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', beranda_index),
    path('beranda/', include(beranda)),
    path('distribusi/', include(distribusi)),
    path('laporan/', include(laporan)),
    path('registration/', include(registration)),
    path('staff/', include(staff)),
    path('user/', include(user)),
]

beranda/urls.py
from django.urls import path
from .views import beranda, covid_api, login_beranda, logout_account

app_name = 'beranda'

urlpatterns = [
    path('', beranda, name='beranda'),
    path('login', login_beranda, name = 'login'),
    path('covid_api', covid_api, name = "covid_api"),
    path('logout/', logout_account, name='logout_beranda')
]

distribusi/urls.py
from django.urls import path
from .views import add_previous_location, all_bansos, bansos_from_id, bansos_group_detail, generate_bansos, generate_bansos_groups, generate_json_bansos_location, get_area_json, get_tracking_resp, mob_generate_bansos, mob_get_tracking_admin, mobile_get_bansos_groups, mobile_register_area, register_area, tracking_admin_dashboard, update_shipping

app_name = 'distribusi'

urlpatterns = [
    path('', all_bansos, name='all_bansos'),
    path('generate-bansos/', generate_bansos, name='generate_bansos'),
    path('update-shipping/<uuid:bansos_group_id>/', update_shipping, name='update_shipping'),
    path('detail-bansos/<uuid:bansos_group_id>/', bansos_group_detail, name='bansos_group_detail'),
    path('tracking-admin-dashboard/', tracking_admin_dashboard, name='tracking_admin_dashboard'),
    path('get-previous-location/', generate_json_bansos_location, name="generate_json_bansos_location"),
    path('get-bansos-groups/', generate_bansos_groups, name="generate_bansos_groups"),
    path('register-area/', register_area, name='register_area'),
    path('get-area-information/', get_area_json, name='get_area_json'),
    path('mob-get-bansos-groups/', mobile_get_bansos_groups, name="mobile_get_bansos_groups"),
    path('mob-bansos-from-id/', bansos_from_id, name="bansos_from_id"),
    path('mob-register-area/', mobile_register_area),
    path('mob-register-bansos/', mob_generate_bansos),
    path('mob-get-admin/', mob_get_tracking_admin),
    path('mob-get-trackings/', get_tracking_resp),
    path('mob-add-prev-location/', add_previous_location),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

staff/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import accept, admin_info, getMasyarakat, mobile_get_admin_info, mobile_get_user_from_tele, mobile_get_verification_responsibility, mobile_verify_user, user_verify, verification, reject

urlpatterns = [
    path('admin-info', admin_info, name = 'add_info'),
    path('verification', verification, name = 'verification'),
    path('reject/<str:user_telephone>', reject, name = 'rejected'),
    path('user-verify/<str:user_telephone>', user_verify, name = 'verified'),
    path('accept/<str:user_telephone>', accept, name = 'accepted'),
    path('get-masyarakat/<str:admin_tele>', getMasyarakat, name = 'get-masyarakat'),
    path('flutter-get-admin-info/', mobile_get_admin_info),
    path('flutter-get-tracking-responsibilities/', mobile_get_verification_responsibility),
    path('flutter-verification-citizen/', mobile_verify_user),
    path('flutter-get-user-from-tele/', mobile_get_user_from_tele)
]

staff/models.py
from django.db import models
from django.db.models.fields import CharField


# Create your models here.
# class Admin(models.Model):
#     owning_user = models.OneToOneField(User, on_delete=models.CASCADE)
#     type = models.CharField(max_length=20)

class Admin(models.Model):
    owning_user = models.OneToOneField("user.Account", on_delete=models.CASCADE)
    type = models.CharField(max_length=20)
    name = models.CharField(max_length=20, null=True)

    # This attribute is dedicated only for tracking admin.
    # It indicates whether a tracking admin is currently 'guarding'
    # a bansos group or not.
    is_occupied = models.BooleanField(default=False)

staff/views.py
from importlib import import_module
from django.conf import settings
from django.shortcuts import redirect, render
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from user.models import AccountMasyarakat
from .models import Admin
from django.http.response import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from user.models import Account
import json


@login_required()
def admin_info(request):
    adInfo = request.user
    try:
        admin = adInfo.admin
    
    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    response = {'Admin_Info' : adInfo}
    return render(request, 'bansospeduli_admininfo.html', response)

@login_required()
def verification(request):

    adInfo = request.user
    try:
        admin = adInfo.admin
    
    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    if adInfo.admin.type != 'verification':
        return HttpResponseForbidden()

    response = {'Admin_Info' : adInfo}

    if adInfo.admin.type=='verification':
        assign_user = adInfo.admin.accountmasyarakat_set.all()
        response['assigned'] = assign_user

    return render(request, 'bansospeduli_Dashboard.html', response)

@login_required()
def user_verify(request, user_telephone):
    user = request.user

    try:
        admin_object = user.admin

    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    if admin_object.type != 'verification':
        return HttpResponseForbidden()

    # Get Account to verify
    user_to_verify = Account.objects.get(telephone = user_telephone)

    # Try retrieving account masyarakat 
    try:
        account_masyarakat = user_to_verify.accountmasyarakat
    
    except:
        return HttpResponse("The user you are trying to edit is not a Citizen.")


    if account_masyarakat.verifying_admin != admin_object:
        return render(request, '403.html')

    response = {'user':user, 'user_to_verify': user_to_verify}
    return render(request, 'bansospeduli_verification.html', response)

@login_required()
def reject(request, user_telephone):
    user = request.user

    try:
        admin_object = user.admin

    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    if admin_object.type != 'verification':
        return HttpResponseForbidden()

    # Get Account to verify
    user_to_verify = Account.objects.get(telephone = user_telephone)

    # Try retrieving account masyarakat
    try:
        account_masyarakat = user_to_verify.accountmasyarakat

    except:
        return HttpResponse("The user you are trying to edit is not a Citizen.")

    if account_masyarakat.verifying_admin != admin_object:
        return HttpResponseForbidden()

    user_to_verify.accountmasyarakat.is_verified = False
    user_to_verify.accountmasyarakat.save()

    return redirect('verification')

@login_required()
def accept(request, user_telephone):
    user = request.user

    try:
        admin_object = user.admin

    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    if admin_object.type != 'verification':
        return HttpResponseForbidden()
        
    # Get Account to verify
    user_to_verify = Account.objects.get(telephone = user_telephone)

    # Try retrieving account masyarakat
    try:
        account_masyarakat = user_to_verify.accountmasyarakat

    except:
        return HttpResponse("The user you are trying to edit is not a Citizen.")
    
    if account_masyarakat.verifying_admin != admin_object:
        return HttpResponseForbidden()

    user_to_verify.accountmasyarakat.is_verified = True
    user_to_verify.accountmasyarakat.save() 
    
    return redirect('verification')

def getMasyarakat(request, admin_tele):
    admin_account_object = Account.objects.get(telephone=admin_tele)
    data = [(i.owning_user.telephone, i.is_verified, i.name) for i in AccountMasyarakat.objects.filter(verifying_admin=admin_account_object.admin)]
    dataSer = json.dumps(data)
    return HttpResponse(dataSer, content_type="application/json")

def mobile_get_admin_info(request):
    '''
    Method to return name, admin_type, and registered phone number
    '''
    # request dictionary
    
    if request.method == 'GET':
        data = request.GET
        session_id = data.get('session_id')

        engine = import_module(settings.SESSION_ENGINE)
        sessionstore = engine.SessionStore
        session = sessionstore(session_id)

        admin_telephone = session.get('_auth_user_id')


        # Get corresponding account from telephone
        corresponding_account = Account.objects.get(telephone=admin_telephone)

        # Get corresponding admin object from account
        corresponding_admin = corresponding_account.admin

        # Construct dictionary to be returned as JSON
        data_dictionary = {
            'name':corresponding_admin.name,
            'admin_type':corresponding_admin.type,
            'phone_number':corresponding_account.telephone
        }

        # json_data = json.dumps(data_dictionary)

        return JsonResponse(data_dictionary, safe=False)

def mobile_get_verification_responsibility(request):
    '''
    Method to return the list of users to verify from 
    a verification admin session (phone number)
    '''
    if request.method == 'GET':
        data = request.GET
        session_id = data.get('session_id')

        engine = import_module(settings.SESSION_ENGINE)
        sessionstore = engine.SessionStore
        session = sessionstore(session_id)

        # Get the telephone from data dictionary
        admin_telephone = session.get('_auth_user_id')

        # Get corresponding account from telephone
        corresponding_account = Account.objects.get(telephone=admin_telephone)

        # Get corresponding admin from account
        corresponding_admin = corresponding_account.admin

        # Get accounts who were assinged to the corresponding admin
        resp_accounts = AccountMasyarakat.objects.filter(verifying_admin=corresponding_admin)

        json_data = serializers.serialize('json', resp_accounts)

        return HttpResponse(json_data, content_type='application/json')

@csrf_exempt
def mobile_verify_user(request):

    if request.method == 'POST':
        try:
            data = json.loads(request.body.decode("utf-8"))

            # Assign data to corresponding variables
            citizen_telephone = data.get('telephone')
            verification_result = data.get('verification_result')

            # Get corresponding account from telephone
            corresponding_account = Account.objects.get(telephone=citizen_telephone)

            # Get corresponding masyarakat from account
            corresponding_masyarakat = corresponding_account.accountmasyarakat

            if verification_result == 'verified':
                corresponding_masyarakat.is_verified=True
            else:
                corresponding_masyarakat.is_verified=False
            
            corresponding_masyarakat.save()
            
            return JsonResponse({'is_successful':True, 'error':None})
            
        except Exception as exc:
            return JsonResponse({'is_successful':False, 'error':str(exc)})

def mobile_get_user_from_tele(request):
    
    if request.method == 'GET':
        
        data = request.GET

        # Assign data to corresponding variables
        citizen_telephone = data.get('telephone')

        # Get corresponding account from telephone
        corresponding_account = Account.objects.get(telephone=citizen_telephone)

        # Get corresponding masyarakat from account
        corresponding_masyarakat = corresponding_account.accountmasyarakat

        data_dictionary = {
            'phone_number':corresponding_account.telephone,
            'name':corresponding_masyarakat.name,
            'nik': corresponding_masyarakat.NIK,
            'sktm': corresponding_masyarakat.SKTMLink,
            'bukutabungan':corresponding_masyarakat.bukuTabunganLink,
            'location':corresponding_masyarakat.partOf.area_name,
            'isVerified':corresponding_masyarakat.is_verified
        }
        return JsonResponse(data_dictionary, safe=False)

staff/templates/bansospeduli_Dashboard.html
{% extends 'base8000.html' %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'distribusi/distribusi-bansos.css' %}">
    <script src='https://code.jquery.com/jquery-3.4.1.min.js' type='text/javascript' defer></script>
    <script src="{%static 'bansospeduli-verification.js'%}"defer></script>
    <link href="{%static 'verif.css'%}" rel="stylesheet">
{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a href="{% url 'add_info' %}" class="nav-link">My Profile</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'verification' %}" class="nav-link active">Verification Dashboard</a>
    </li>
{% endblock %}

{% block rightnav %}
    <li class="nav-item">
        <div class="nav-link" style="color:white;">
            Hello, {{ user.admin.name }} 
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:logout_beranda' %}">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF" class="svg-as-button"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/></svg>
        </a>
    </li>
{% endblock %}

{% block body %}
        <input type="hidden" value="{{ user.telephone }}" id="admin_tele">
        <div class="title-container-verif">
            <span class="special-title">Verification Dashboard</span>
        </div>
        <div class="row"
        style="padding-top: 25px;">
            <div class="col">
                <div class="container">
                    <ul class="list-group-flush">
                        <div class="card-header card-header-dashboard">
                            Unverified User
                        </div>
                        <li class="list-group-item" id="unverified_user_container">
                            
                        </li>
                    </ul>
                </div>
            </div>
            
            <div class="col">
                <div class="container">
                    <ul class="list-group-flush">
                        <div class="card-header card-header-dashboard">
                            Verified User
                        </div>
                        <li class="list-group-item" id="verified_user_container"></li>
                    </ul>
                </div>
            </div>
            </div>
{% endblock %}

staff/templates/bansospeduli_admininfo.html
{% extends 'base8000.html' %}
{% block head %}
    {% load static %}
    <script src='https://code.jquery.com/jquery-3.4.1.min.js' type='text/javascript' defer></script>
    <link rel="stylesheet" href="{%static 'admin-dashboard.css'%}">
{% endblock %}

    

{% block title %}Admin Information{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a href="{% url 'add_info' %}" class="nav-link active">My Profile</a>
    </li>
    {% if Admin_Info.admin.type == "generator" %}
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">Generator Dashboard</a>
            <ul class="dropdown-menu" id="generator-dropdown">
                <li class="dropdown-item">
                    <a href="{% url 'distribusi:all_bansos' %}" class="dropdown-item">Dashboard</a>
                </li>
                <li class="dropdown-item">
                    <a href="{% url 'distribusi:register_area' %}" class="dropdown-item">Register Area</a>
                </li>
            </ul>
        </li>
    {% elif Admin_Info.admin.type == "tracker" %}
        <li class="nav-item">
            <a href="{% url 'distribusi:tracking_admin_dashboard' %}" class="nav-link">Tracking Dashboard</a>
        </li>
    {% elif Admin_Info.admin.type == "verification" %}
        <li class="nav-item">
            <a href="{% url 'verification' %}" class="nav-link">Verification Dashboard</a>
        </li>
    {% elif Admin_Info.admin.type == "customer-service"%}
        <li class="nav-item">
            <a href="{% url 'laporan-admin' %}" class="nav-link">Reports Dashboard</a>
        </li>
    {%endif%}
{% endblock %}

{% block rightnav %}
    <li class="nav-item">
        <div class="nav-link" style="color:white;">
            Hello, {{ Admin_Info.admin.name }} 
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:logout_beranda' %}">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF" class="svg-as-button"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/></svg>
        </a>
    </li>
{% endblock %}

{% block body %}
        <div class="parent">
        
          {% if Admin_Info %}
            <div class="container">
                <div class="card">
                    <div class="profile-header"><h2>My Profile</h2></div>
                    <div class="profile-picture">
                    </div>
                    <div class="badge">
                        <h3 class="badge-text">Admin</h3>
                    </div>
                    <div class="name">
                        <h4>{{ Admin_Info.admin.name }}</h4>
                    </div>
                    <div class="type">
                        <h5>{{ Admin_Info.admin.type }}</h5>
                    </div>
                    <div class="telephone">
                        <h4><span>Registered Phone Number: </span><span>{{ Admin_Info.telephone }}</span></h4>
                    </div>
                    <a class="btn btn-danger" href="/beranda/logout">Log Out</a>
                </div>
            </div>
        </div>
        {% endif %}
        </div>
        
{% endblock %}
</html>

staff/templates/bansospeduli_verification.html
{% extends 'base8000.html' %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'distribusi/distribusi-bansos.css' %}">
    <script src='https://code.jquery.com/jquery-3.4.1.min.js' type='text/javascript' defer></script> 
    <link rel="stylesheet" href="{% static 'verif.css' %}">
{% endblock %}

    
{% block title %}Verify{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a href="{% url 'add_info' %}" class="nav-link">My Profile</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'verification' %}" class="nav-link">Verification Dashboard</a>
    </li> 
{% endblock %}

{% block rightnav %}
    <li class="nav-item">
        <div class="nav-link" style="color:white;">
            Hello, {{ user.admin.name }} 
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:logout_beranda' %}">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF" class="svg-as-button"><path d="M0 0h24v24H0z" fill="none"/><path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/></svg>
        </a>
    </li>
{% endblock %}

{% block body %}
      <div class="title-container">
        <h1>User Information</h1>
        <h2>Telephone Number : {{ user_to_verify }}</h2>
        </div>
          <section class="adjusted-section">
            <div class="special-form-container">
              <div style="font-weight: bold;">NAME </div>
                <div class="row"
                style = "background-color:lightgray; border-radius: 5px; margin-left: 1px;margin-right: 1px;">
                  <span
                  style="padding: 5px;">{{user_to_verify.accountmasyarakat.name}}</span>
                </div>
                <div style="font-weight: bold; padding-top: 5px;">NIK </div>
                <div class="row"
                  style = "background-color:lightgray; border-radius: 5px; margin-left: 1px;margin-right: 1px;">
                  <span 
                  style="padding: 5px">{{user_to_verify.accountmasyarakat.NIK}}</span>
                </div>
                <div style="font-weight: bold; padding-top: 5px;">SKTM </div>
                <div class="row"
                  style = "background-color:lightgray; border-radius: 5px; margin-left: 1px;margin-right: 1px;">
                  <span style="padding: 5px;">{{user_to_verify.accountmasyarakat.SKTMLink}}</span>
                </div>
                <div style="font-weight: bold; padding-top: 5px;">BUKU TABUNGAN </div>
                <div class="row"
                  style = "background-color:lightgray; border-radius: 5px; margin-left: 1px;margin-right: 1px;">
                  <span style="padding: 5px;"> {{user_to_verify.accountmasyarakat.bukuTabunganLink}}</span>
                </div>
                <div style="font-weight: bold; padding-top: 5px;">LOCATION </div>
                <div class="row"
                  style = "background-color:lightgray; border-radius: 5px; margin-left: 1px;margin-right: 1px;">
                  <span style="padding: 5px;">{{user_to_verify.accountmasyarakat.partOf.area_name}} </span>
                </div>


                    
                    <!-- <div class="card-header">
                        <h1>Name : {{user.accountmasyarakat.name}}</h1>
                        <h2>{{user}}</h2>
                    </div> -->
                    
                    <!-- <div class="card-body">
                        <h5 class="card-title"> NIK  : {{user.accountmasyarakat.NIK}} </h5>
                        <h5 class="card-title"> SKTM :{{user.accountmasyarakat.SKTMLink}} </h5>
                        <h5 class="card-title"> Buku Tabungan : {{user.accountmasyarakat.bukuTabunganLink}} </h5>
                        <h5 class="card-title"> Location : {{user.accountmasyarakat.partOf.area_name}} </h5>
                    </div>
                    
                </div> -->
                <div class="text-center" id="firstextcenter">
                </div>
            </div>
        </div>

    </div>

    <div class="text-center" id="secondtextcenter">
        <button type="button" class="btn btn-success" onclick="window.location.href='../accept/{{user_to_verify.telephone}}'">
            Verify User
        </button>
        <button type="button" class="btn btn-danger" onclick="window.location.href='../reject/{{user_to_verify.telephone}}'">
            Reject User
        </button>
    </div>
 

   
{% endblock %}