bansospeduli/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

import beranda.urls as beranda
import distribusi.urls as distribusi
import laporan.urls as laporan
import registration.urls as registration
import staff.urls as staff
import user.urls as user
from beranda.views import beranda as beranda_index

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', beranda_index),
    path('beranda/', include(beranda)),
    path('distribusi/', include(distribusi)),
    path('laporan/', include(laporan)),
    path('registration/', include(registration)),
    path('staff/', include(staff)),
    path('user/', include(user)),
]

beranda/urls.py
from django.urls import path
from .views import beranda, covid_api, login_beranda, logout_account

app_name = 'beranda'

urlpatterns = [
    path('', beranda, name='beranda'),
    path('login', login_beranda, name = 'login'),
    path('covid_api', covid_api, name = "covid_api"),
    path('logout/', logout_account, name='logout_beranda')
]

distribusi/urls.py
from django.urls import path
from .views import add_previous_location, all_bansos, bansos_from_id, bansos_group_detail, generate_bansos, generate_bansos_groups, generate_json_bansos_location, get_area_json, get_tracking_resp, mob_generate_bansos, mob_get_tracking_admin, mobile_get_bansos_groups, mobile_register_area, register_area, tracking_admin_dashboard, update_shipping

app_name = 'distribusi'

urlpatterns = [
    path('', all_bansos, name='all_bansos'),
    path('generate-bansos/', generate_bansos, name='generate_bansos'),
    path('update-shipping/<uuid:bansos_group_id>/', update_shipping, name='update_shipping'),
    path('detail-bansos/<uuid:bansos_group_id>/', bansos_group_detail, name='bansos_group_detail'),
    path('tracking-admin-dashboard/', tracking_admin_dashboard, name='tracking_admin_dashboard'),
    path('get-previous-location/', generate_json_bansos_location, name="generate_json_bansos_location"),
    path('get-bansos-groups/', generate_bansos_groups, name="generate_bansos_groups"),
    path('register-area/', register_area, name='register_area'),
    path('get-area-information/', get_area_json, name='get_area_json'),
    path('mob-get-bansos-groups/', mobile_get_bansos_groups, name="mobile_get_bansos_groups"),
    path('mob-bansos-from-id/', bansos_from_id, name="bansos_from_id"),
    path('mob-register-area/', mobile_register_area),
    path('mob-register-bansos/', mob_generate_bansos),
    path('mob-get-admin/', mob_get_tracking_admin),
    path('mob-get-trackings/', get_tracking_resp),
    path('mob-add-prev-location/', add_previous_location),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

distribusi/models.py
from django.db import models
import uuid

STATUS_CHOICE = [
    ('queued', 'queued'),
    ('sent', 'sent'),
    ('received', 'received'),
]

class Area(models.Model):
    area_code = models.CharField(max_length=20, primary_key=True)

    area_name = models.CharField(max_length=20)

class BansosGroup(models.Model):
    responsible_admin = models.ForeignKey('staff.Admin', on_delete=models.RESTRICT, default='')
    id_bansos_group = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # Kalau areanya hilang, harusnya Bansosnya juga hilang :)

    # Receiving provinsi marks the target provinsi
    receiving_provinsi = models.ForeignKey(Area, 
        on_delete=models.SET_DEFAULT, default='NULL')

    status = models.CharField(max_length=10,  
            default='queued')

    kelurahan = models.CharField(max_length=20)
    kecamatan = models.CharField(max_length=20)
    kabupaten_kota = models.CharField(max_length=20, null=True)
    # The variable provinsi marks the CURRENT provinsi
    provinsi = models.CharField(max_length=20)

    destination_kelurahan = models.CharField(max_length=20, null=True)
    destination_kecamatan = models.CharField(max_length=20, null=True)
    destination_kabupaten_kota = models.CharField(max_length=20, null=True)

    total_receiver = models.BigIntegerField(default=0)
    # JSON to store dictionary (multivalued), 
    # Key --> Jenis
    # Value --> Jumlah
    bentuk_bantuan = models.JSONField(default=dict)
    satuan_bantuan = models.JSONField(default=dict)

   

class Bansos(models.Model):
    owning_group = models.ForeignKey(BansosGroup,
        on_delete=models.CASCADE,
    )

    id_bansos = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    received_by = models.ForeignKey('user.AccountMasyarakat', on_delete=models.CASCADE, default=None)
    is_reported = models.BooleanField(default=False)

class BansosPreviousLocation(models.Model):
    bansos_group = models.ForeignKey(BansosGroup, on_delete=models.CASCADE)
    kelurahan = models.CharField(max_length=20)
    kecamatan = models.CharField(max_length=20)
    kabupaten_kota = models.CharField(max_length=20, null=True)
    provinsi = models.CharField(max_length=20)
    status = models.CharField(max_length=20, default='queued')
    time_stamp = models.DateTimeField(auto_now=True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import uuid

class MyAccountManager(BaseUserManager):
    def create_user(self, telephone, password=None):
        if not telephone:
            raise ValueError("Users must have a telephone number")
        
        user = self.model(
            telephone=telephone,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, telephone, password):
        user = self.create_user(
            telephone=telephone,
            password=password,
        )
        user.is_staff = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    telephone = models.CharField(max_length=20,primary_key=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_citizen = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    USERNAME_FIELD = 'telephone'
    REQUIRED_FIELDS = []
    
    objects = MyAccountManager()

    def __str__(self):
        return self.telephone
    
    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return True

# Create your models here.
class AccountMasyarakat(models.Model):
    owning_user = models.OneToOneField(Account, on_delete=models.CASCADE, primary_key=True)
    is_verified = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    NIK = models.CharField(max_length=16)
    SKTMLink = models.CharField(max_length=200)
    bukuTabunganLink = models.CharField(max_length=200)
    partOf = models.ForeignKey("distribusi.Area", 
        on_delete=models.RESTRICT, 
        default='NULL'
    )
    verifying_admin = models.ForeignKey("staff.Admin", on_delete=models.SET_DEFAULT, default=None)

distribusi/views.py
from importlib import import_module
from json.decoder import JSONDecoder
from django.conf import settings
from django.http.response import HttpResponse, HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators import csrf
from user.models import Account
from staff.models import Admin
from .models import Area, Bansos, BansosGroup, BansosPreviousLocation, STATUS_CHOICE
from laporan.forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.db import IntegrityError
from django.contrib.sessions.backends.db import SessionStore
import json
import time

# UPDATED
@login_required()
def tracking_admin_dashboard(request):
    # Add additional variable if admin is a tracking admin and is currently occupied
    user = request.user

    try:
        admin = user.admin
    
    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    if admin.type != 'tracker':
        return HttpResponseForbidden()

    bansos_all = admin.bansosgroup_set.all()
    context = {'tracking_admin':admin, 'bansos_all':bansos_all}
    
    return render(request, 'tracking-admin-dashboard.html', context)

# UPDATED
@login_required()
def all_bansos(request):
    '''
    Function as index for distribusi application,
    it displays all the bansos generated (on queue, sent,received)
    '''
    user = request.user

    try:
        admin = user.admin
    
    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    if admin.type != 'generator':
        return HttpResponseForbidden()

    context = {'admin':admin}

    return render(request, 'bansos-index.html', context)

def check_number(string_number: str) -> bool:
    try:
        float(string_number)
        return float(string_number) > 0

    except ValueError:
        return False


# UPDATED
@login_required()
def generate_bansos(request):
    '''
    Function to generate bansos. It will save the bansos generated
    for a specific area and assign it to citizens of that area.
    It will also assign a tracking admin to the bansos generated.
    '''
    user = request.user

    post_request_errors = []

    # Authentication

    # Reject if user is not an admin
    try:
        user_admin_account = Admin.objects.get(owning_user=user)

    except Admin.DoesNotExist:
        return HttpResponseForbidden()
    
    if user_admin_account.type != 'generator':
        return HttpResponseForbidden()

    
    if request.method == 'POST':
        # Input validation
        # Sent-from information
        current_kelurahan = request.POST.get('input_kelurahan')
        current_kecamatan = request.POST.get('input_kecamatan')
        current_kabupaten_kota = request.POST.get('input_kabupaten_kota')
        current_provinsi = request.POST.get('input_provinsi')

        # Sent-to information
        target_kelurahan = request.POST.get('input_kelurahan_target')
        target_kecamatan = request.POST.get('input_kecamatan_target')
        target_kabupaten_kota = request.POST.get('input_kabupaten_kota_target')

        area_code = request.POST.get('area')

        tracking_admin_tele = request.POST.get('tracking-admin')
        
        error_flag = False

        # Check if any of the fields are empty
        if not current_kelurahan:
            post_request_errors.append("Kelurahan Field Must Not Be Empty!")
            error_flag = True

        if not current_kecamatan:
            post_request_errors.append("Kecamatan Field Must Not Be Empty!")
            error_flag = True

        if not current_provinsi:
            post_request_errors.append("Provinsi Field Must Not Be Empty!")
            error_flag = True

        if not area_code:
            post_request_errors.append("Area Field Must Not Be Empty!")
            error_flag = True

        if not tracking_admin_tele:
            post_request_errors.append("Tracking Admin Field Must Not Be Empty!")
            error_flag = True
        
        if not error_flag:
            # Check if bansos type is empty
            # Create a dictionary (to be converted to JSON) from the given bansos-type and values
            counter_value = int(request.POST.get('item-counter'))
            jenis_bantuan = {}
            satuan_bantuan = {}

            bansos_error_flag = False

            # Iterate through the user-added fields, check if it contains valid value
            for type_count in range(counter_value+1):
                bantuan_name = request.POST.get(f"type_input{type_count}")
                bantuan_value = request.POST.get(f"type_value{type_count}")
                bantuan_unit = request.POST.get(f"type_unit{type_count}")

                if bantuan_name and bantuan_value and bantuan_unit:
                    # Insert value to dictionary when validated
                    jenis_bantuan[bantuan_name.strip().lower()] = bantuan_value.strip().lower()
                    satuan_bantuan[bantuan_name.strip().lower()] = bantuan_unit.strip().lower()

                    if not check_number(bantuan_value):
                        bansos_error_flag = True
                
                # If only bantuan_name is given
                elif bantuan_name:
                    bansos_error_flag = True

                ## If either bantuan_value or bantuan_unit is not empty, but bantuan_name is empty,
                ## the entry will be neglected
            
            # Raise error if no jenis bantuan is given
            if not jenis_bantuan or not satuan_bantuan or bansos_error_flag:
                post_request_errors.append("Bansos information is invalid.")
                
            else:
                # Get area from the given area code
                area_object = Area.objects.get(area_code=area_code)

                # Get tracking admin from the given telephone number
                admin_object = Account.objects.get(telephone=tracking_admin_tele).admin

                # Get all rightful bansos receiver in the area
                citizens = area_object.accountmasyarakat_set.filter(is_verified=True)

                # Clean current provinsi data
                current_provinsi_name = current_provinsi.split(',')[1]

                # Reject generation of bansos if no rightful citizens in the area
                if not len(citizens) > 0:
                    post_request_errors.append("Area has no citizens.")

                else:
                    # Generate and Save BansosGroup
                    new_bansos_group = BansosGroup(
                        responsible_admin=admin_object,
                        receiving_provinsi=area_object,
                        status='queued',
                        kelurahan=current_kelurahan,
                        kecamatan=current_kecamatan,
                        kabupaten_kota=current_kabupaten_kota,
                        provinsi=current_provinsi_name,
                        destination_kelurahan=target_kelurahan,
                        destination_kecamatan=target_kecamatan,
                        destination_kabupaten_kota=target_kabupaten_kota,
                        total_receiver=len(citizens),
                        bentuk_bantuan=jenis_bantuan,
                        satuan_bantuan=satuan_bantuan,
                    )

                    # Generate previous location data
                    bansos_location = BansosPreviousLocation(
                        bansos_group=new_bansos_group,
                        kelurahan=current_kelurahan,
                        kecamatan=current_kecamatan,
                        kabupaten_kota=current_kabupaten_kota,
                        provinsi=current_provinsi_name
                    )

                    # Save to database
                    new_bansos_group.save()
                    bansos_location.save()

                    # Generate individual bansos for each rightful citizens
                    for citizen in citizens:
                        new_bansos = Bansos(
                            owning_group=new_bansos_group,
                            received_by=citizen
                        )

                        new_bansos.save()
                    
                    # As the tracking staff is selected to track the just-generated bansos,
                    # changed is_occupied flag to True
                    admin_object.is_occupied = True
                    admin_object.save()

                    return redirect('distribusi:all_bansos')
    
    
    # Retrieve the query set of all tracking admins, 
    # and obtain its corresponding account
    tracking_admins = Admin.objects.filter(type="tracker")

    tracking_accounts = [ tracking.owning_user for tracking in tracking_admins ]

    # Retrieve the query set of all areas for bansos destination
    areas = Area.objects.all()

    context = {'tracking_accounts': tracking_accounts, 'areas': areas, 'generating_account':user, 'errors':post_request_errors}

    return render(request, 'generate-bansos.html', context)

# UPDATED
@login_required()
def update_shipping(request, bansos_group_id):
    '''
    Function to update the current shipping position of the bansos
    group. It will take bansos_group_id in url parameter.
    '''
    post_request_errors = []

    user = request.user
    # Authorization Validation
    try:
        user_admin_account = Admin.objects.get(owning_user=user)

    except Admin.DoesNotExist:
        return HttpResponseForbidden()

    # Check if user is not of type tracking admin
    if user_admin_account.type != 'tracker':
        return HttpResponseForbidden()

    # Get corresponding bansos_group from given bansos_group_id
    corresponding_group = BansosGroup.objects.get(id_bansos_group=bansos_group_id)

    # Check if bansos does not belong to the current admin

distribusi/templates/bansos-index.html
{% extends 'base8000.html' %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'distribusi/distribusi-bansos.css' %}">
    <script src='https://code.jquery.com/jquery-3.4.1.min.js' type='text/javascript' defer></script>
    <script src="{% static 'distribusi/js/bansos-index.js' %}" defer></script>
    <script src="{% static 'distribusi/js/toggler-handler.js' %}" defer></script>
{% endblock %}

{% block title %}All Bansos{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a href="{% url 'add_info' %}" class="nav-link">My Profile</a>
    </li>
    <li class="nav-item dropdown">
        <a href="#" class="nav-link active dropdown-toggle" role="button" data-bs-toggle="dropdown">Generator Dashboard</a>
        <ul class="dropdown-menu" id="generator-dropdown">
            <li class="dropdown-item">
                <a href="{% url 'distribusi:all_bansos' %}" class="dropdown-item">Dashboard</a>
            </li>
            <li class="dropdown-item">
                <a href="{% url 'distribusi:register_area' %}" class="dropdown-item">Register Area</a>
            </li>
        </ul>
    </li>
{% endblock %}

{% block rightnav %}
    <li class="nav-item">
        <div class="nav-link" style="color:white;">
            Hello, {{ user.admin.name }} 
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:logout_beranda' %}">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF" class="svg-as-button">
                <path d="M0 0h24v24H0z" fill="none"/>
                <path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/>
            </svg>
        </a>
    </li>
{% endblock %}
    
{% block body %}
    <div class="title-container">
        <h1>Distribution Dashboard</h1>
        <a href="{% url 'distribusi:generate_bansos' %}" class="btn btn-curious btn-curious-bordered">Generate Bansos</a>
        <a href="{% url 'distribusi:register_area' %}" class="btn btn-curious btn-curious-bordered">Register Area</a>
        <div class="btn-group">
            <button class="btn btn-curious without-margin btn-curious-bordered btn-curious-selected" onclick="toggleQueued()" id="queued-dash-btn">Queued</button>
            <button class="btn btn-curious without-margin btn-curious-bordered btn-curious-selected" onclick="toggleSent()" id="sent-dash-btn">Sent</button>
            <button class="btn btn-curious without-margin btn-curious-bordered btn-curious-selected" onclick="toggleReceived()" id="received-dash-btn">Received</button>
        </div>
    </div>
    <section id="queued-bansos-section" class="adjusted-section" id="queued-bansos-section">
        <div class="special-form-container grid-padding">
            <span class="bansos-stat-title" id="queued-title">Queued Bansos Group</span>
            <div class="bansos-grid-container" id="queued-bansos-grid"></div>
        </div>
    </section>
    <section class="bansos-list-container adjusted-section" id="sent-bansos-section">
        <div class="special-form-container grid-padding">
            <span class="bansos-stat-title" id="sent-title">Sent Bansos Group</span>
            <div class="bansos-grid-container" id="sent-bansos-grid"></div>
        </div>
    </section>
    <section class="bansos-list-container adjusted-section" id="received-bansos-section">
        <div class="special-form-container grid-padding">
            <span class="bansos-stat-title" id="received-title">Received Bansos Group</span>
            <div class="bansos-grid-container" id="received-bansos-grid"></div>
        </div>
    </section>
{% endblock %}

distribusi/templates/tracking-admin-dashboard.html
{% extends 'base8000.html' %}
{% block head %}
    {% load static %}
    <link href="{% static 'distribusi/distribusi-bansos.css' %}" rel="stylesheet">
    <script src='https://code.jquery.com/jquery-3.4.1.min.js' type='text/javascript' defer></script>
    <script src="{% static 'distribusi/js/toggler-handler.js' %}" defer></script>
{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a href="{% url 'add_info' %}" class="nav-link">My Profile</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'distribusi:tracking_admin_dashboard' %}" class="nav-link active">Tracking Dashboard</a>
    </li>
{% endblock %}

{% block rightnav %}
    <li class="nav-item">
        <div class="nav-link" style="color:white;">
            Hello, {{ user.admin.name }} 
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:logout_beranda' %}">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF" class="svg-as-button">
                <path d="M0 0h24v24H0z" fill="none"/>
                <path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/>
            </svg>
        </a>
    </li>
{% endblock %}

{% block title %}Tracking Admin Dashboard{% endblock %}
{% block body %}
    <div class="blue-box">
        <div class="preliminary-container">
            <h1>Tracking Admin Dashboard</h1>
        </div>
    </div>
    <div class="enclosing-container">

    <div class="tracking-card-container">
        <h3>Currently Active Bansos</h3>
        {% for bansos in bansos_all %}
            {% if bansos.status != 'received' %}
                <div class="card tracking-card">
                    <div class="card-header">
                        {{ bansos.status }} 
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ bansos.receiving_provinsi.area_name }} - {{ bansos.bansospreviouslocation_set.all.0.time_stamp }}</h5>
                        <p class="card-text">Destination of this Bansos is {{ bansos.receiving_provinsi.accountmasyarakat_set.all | length }} citizens in 
                            {{ bansos.receiving_provinsi.area_name }}. This bansos will be sent to {{ bansos.destination_kelurahan }}, {{ bansos.destination_kecamatan }}, {{ bansos.destination_kabupaten_kota }}, {{ bansos.receiving_provinsi.area_name }}.</p>
                        <a href="{% url 'distribusi:update_shipping' bansos.id_bansos_group %}" class="btn btn-primary">Update
                            <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF">
                                <g><rect fill="none" height="24" width="24" x="0"/></g><g><g><g>
                                <path d="M21,10.12h-6.78l2.74-2.82c-2.73-2.7-7.15-2.8-9.88-0.1c-2.73,2.71-2.73,7.08,0,9.79s7.15,2.71,9.88,0 C18.32,15.65,19,14.08,19,12.1h2c0,1.98-0.88,4.55-2.64,6.29c-3.51,3.48-9.21,3.48-12.72,0c-3.5-3.47-3.53-9.11-0.02-12.58 s9.14-3.47,12.65,0L21,3V10.12z M12.5,8v4.25l3.5,2.08l-0.72,1.21L11,13V8H12.5z"/>
                                </g></g></g>
                            </svg>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <br>
    <div class="inline-heading">
        <h3>Previous Bansos
            <a >
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-up-circle animated" viewBox="0 0 16 16" id="previous-toggler">
                    <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z"/>
                </svg>
            </a>
        </h3>
        
    </div>
    <div class="tracking-card-container hideable" style="display: none;">
    {% for bansos in bansos_all %}
        {% if bansos.status == 'received' %}
        <div class="card tracking-card">
            <div class="card-header">
                {{ bansos.status }} 
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ bansos.receiving_provinsi.area_name }} - {{ bansos.bansospreviouslocation_set.all.0.time_stamp }}</h5>
                <p class="card-text">Destination of this Bansos is {{ bansos.receiving_provinsi.accountmasyarakat_set.all | length }} citizens in 
                    {{ bansos.receiving_provinsi.area_name }}. This bansos has been sent to {{ bansos.destination_kelurahan }}, {{ bansos.destination_kecamatan }}, {{ bansos.destination_kabupaten_kota }}, {{ bansos.receiving_provinsi.area_name }}.</p>
                <a href="{% url 'distribusi:update_shipping' bansos.id_bansos_group %}" class="btn btn-danger">View History
                    <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF">
                        <g><rect fill="none" height="24" width="24" x="0"/></g><g><g><g>
                        <path d="M21,10.12h-6.78l2.74-2.82c-2.73-2.7-7.15-2.8-9.88-0.1c-2.73,2.71-2.73,7.08,0,9.79s7.15,2.71,9.88,0 C18.32,15.65,19,14.08,19,12.1h2c0,1.98-0.88,4.55-2.64,6.29c-3.51,3.48-9.21,3.48-12.72,0c-3.5-3.47-3.53-9.11-0.02-12.58 s9.14-3.47,12.65,0L21,3V10.12z M12.5,8v4.25l3.5,2.08l-0.72,1.21L11,13V8H12.5z"/>
                    </g></g></g></svg>
                </a>
            </div>
        </div>
        {% endif %}
    {% endfor %}
    </div>
    </div>
{% endblock %}